[alembic]
script_location = core/db/migrations
prepend_sys_path = .
sqlalchemy.url = postgresql+asyncpg://${DB_USER:-trading}:${DB_PASS:-trading_pass}@${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-trading_strategy_center}

[loggers]
keys = root,sqlalchemy,alembic
[handlers]
keys = console
[formatters]
keys = generic
[logger_root]
level = WARN
handlers = console
[logger_sqlalchemy]
level = WARN
qualname = sqlalchemy.engine
[logger_alembic]
level = INFO
qualname = alembic
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
